steps:
  # Build api docker image
  - name: gcr.io/cloud-builders/docker
    waitFor:
      - "-"
    script: >
      docker build
      -t asia-southeast1-docker.pkg.dev/$PROJECT_ID/cartograph-docker/atlas-api:master
      -t asia-southeast1-docker.pkg.dev/$PROJECT_ID/cartograph-docker/atlas-api:git-$SHORT_SHA
      -f atlas-api/Dockerfile
      atlas-api

# Push all the images to our Artifact Registry
images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cartograph-docker/atlas-api:master"
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cartograph-docker/atlas-api:git-$SHORT_SHA"

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
