/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AtlasDocs {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  sourceUrl: string;
  updatedAt: Generated<Timestamp>;
}

export interface AtlasPages {
  createdAt: Generated<Timestamp>;
  description: string | null;
  docId: number;
  id: Generated<number>;
  path: string;
  processedContent: string;
  sourceContent: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  "atlas.docs": AtlasDocs;
  "atlas.pages": AtlasPages;
}
