/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Docs {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  name: string;
  sourceUrl: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Pages {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  docId: number | null;
  id: Generated<number>;
  processedContent: string | null;
  slug: string;
  sourceContent: string | null;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  docs: Docs;
  pages: Pages;
}
