/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Docs {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  name: string;
  source_type: string;
  source_url: string;
  type: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Pages {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  doc_id: number | null;
  id: Generated<number>;
  processed_content: string | null;
  slug: string;
  source_content: string | null;
  title: string;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  docs: Docs;
  pages: Pages;
}
